trigger:
  tags:
    include:
      - '*'

stages:
  - stage: build_and_publish
    pool: default
    variables:
      CI: true
    jobs:
      - deployment: docker_build_and_push
        environment: Production
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  fetchTags: true
                  fetchDepth: 0 # explicitly disable shallow fetch

                - task: PowerShell@2
                  displayName: Compute version number
                  inputs:
                    targetType: 'inline'
                    script: |
                      $gitVersion = git describe
                      $latestMajorTag = ''
                      $latestTag = ''
                      if ($gitVersion -match '^\d.\d.\d$') {
                        # get all tags in semver order oldest to newest
                        $tags = git tag -l --sort=version:refname  | Where-Object { $_ -Match '^\d\.\d\.\d$' }
                        # get the latest released semver
                        $latestVersion = $tags[$tags.Count - 1]
                        # get the latest released semver for the tag being processed
                        $majorVersionMatch =  $gitVersion | Select-String -Pattern '^\d+(?=\.)'
                        $majorVersion = $majorVersionMatch.Matches[0].Value
                        # get latest for this major version
                        $latestMajorVersion = $tags | Where-Object { $_ -Match "^$($majorVersion)(?=\.)" } | Select-Object -Last 1
                        # compute latest tag
                        if([version]$gitVersion -ge [version]$latestMajorVersion) {
                          # it's equal to or greater than
                          # add latest tag to output
                          $latestMajorTag = "$($majorVersion)-latest"
                        }
                        if([version]$gitVersion -ge [version]$latestVersion) {
                          $latestTag = 'latest'
                        }
                      }
                      Write-Host "##vso[task.setvariable variable=fullVersion;]$gitVersion"
                      Write-Host "##vso[task.setvariable variable=latestMajorTag;]$latestMajorTag"
                      Write-Host "##vso[task.setvariable variable=latestTag;]$latestTag"

                - task: Docker@2
                  displayName: Build and push docker image
                  inputs:
                    containerRegistry: 'Docker Hub'
                    repository: 'tkilminster/docker-external-dns'
                    command: 'buildAndPush'
                    dockerfile: '**/Dockerfile'
                    tags: |
                      $(fullVersion)
                      $(latestMajorTag)
                      $(latestTag)